name: Inventory Update
run-name: inventory-update-workflow
on: [push]
jobs:
  Integrity-Check:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: benito2268/chtc_fellowship_inventory_tracking
          ref: main

      # install pyyaml
      - name: Install PyYAML
        run: pip install pyyaml

      # add scripts to the python path
      - name: Setup Python Path
        run: SCRIPT_DIR=$(realpath scripts/shared) ; echo "PYTHONPATH=$PYTHONPATH:$SCRIPT_DIR" >> $GITHUB_ENV

      # run the integrity check
      - name: Run Integrity Check
        run: python3 scripts/data_validator/validate.py data/

  Sheets-Update:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: benito2268/chtc_fellowship_inventory_tracking
          ref: main

      # install python dependancies
      - name: Install Python Packages
        run: pip install pyyaml google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # add scripts to the python path
      - name: Setup Python Path
        run: SCRIPT_DIR=$(realpath scripts/shared) ; echo "PYTHONPATH=$PYTHONPATH:$SCRIPT_DIR" >> $GITHUB_ENV

      # create the google api key
      - name: Create Google API Key
        run: echo ${{ secrets.GOOGLE_API_KEY }} | base64 --decode > token.json

      # run the sheet update script
      - name: Update Google Sheet
        run: python3 scripts/sheets/update_sheet.py

