name: Inventory Update
run-name: inventory-update-workflow
on: [push]
jobs:
  Integrity-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: benito2268/chtc_fellowship_inventory_tracking
          ref: workflow-testing # TODO change this
      - name: Install PyYAML
        run: pip install pyyaml 
      - name: Setup Python Path
        run: SCRIPT_DIR=$(realpath scripts/shared) ; echo "PYTHONPATH=$PYTHONPATH:$SCRIPT_DIR" >> $GITHUB_ENV
      - name: Run Integrity Check
        run: python3 scripts/data_validator/validate.py data/

  Sheets-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          repository: benito2268/chtc_fellowship_inventory_tracking
          ref: workflow-testing # TODO change this
      - name: Install Python Packages
        run: pip install pyyaml google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: Setup Python Path
        run: SCRIPT_DIR=$(realpath scripts/shared) ; echo "PYTHONPATH=$PYTHONPATH:$SCRIPT_DIR" >> $GITHUB_ENV
      - name: Update Google Sheet
        run: python3 scripts/sheets/update_sheet.py

